### ISSUE TITLE
issues with library ? 

### ISSUE THREAD

**Issue by FrankOcean11** [camb416/robocam_control#1]
there seem to be a issue with this line of code 
/_println(portName + " not found, defaulting to: " + serialPorts[0]+".");_/ 
WHY? 
i get a ArrayIndexOutofBoundsException:0 

all i did was copy what was in https://github.com/camb416/robocam_control/blob/master/robocam_control.pde 
and pasted in Processing and hit Run

**Comment by camb416** [comment]
Hi Frank,

The serial library may have changed in Processing since this was authored... though now that I look into the code there's no check confirming that there is >0 serial ports available. The issue is probably that you don't have a serial port available, or that the serial library is not seeing it.

Are you using the same PTZ camera?

**Comment by FrankOcean11** [comment]
no sorry im trying to use a usb camera aside from that my laptop has a built in camera which usually works with processing using the library examples, is their a way to change the camera option in processing and stop it from using the default cam? 

even aside from all this i do have a 8 usb power hub

**Comment by camb416** [comment]
Ah this is not the project for you... it only controls the robotic motion of the camera, it does not actually do anything with the video signal (this camera in particular is not digital).

What you need to do though is just select the correct capture device. This should help you out:

https://processing.org/reference/libraries/video/Capture_list_.html

If you have any questions on that, I'd recommend the Processing Forum, the community is quite helpful on there:

https://forum.processing.org/two/

Good luck!

**Comment by FrankOcean11** [comment]
well yes i guess what i was trying to do was learn from this algorithm so that i may have a idea on how to build my own motorized camera DIY style
